import 'styles/globals.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import StyledComponentsRegistry from 'lib/registry';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
